version: "3.8"
services:

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./tmp/redis:/data

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: app_dev
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: [ "/bin/bash", "-c", "--" ]
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
