version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: app_dev
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: [ "/bin/bash", "-c", "--" ]
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
